project:
  type: website

website:
  title: "spacebun"
  image: "images/spacebunny-banner.svg"
  favicon: "images/spacebunny.svg"
  page-navigation: true
  navbar:
    logo: "images/spacebunny-banner.png"
    title: false
    collapse-below: lg
    background: "#30638E"
    search: true
    left: 
      - text: "{{< iconify fxemoji leftwritinghand >}} Hands-on Exercises"
        menu: 
          - text: Hands-on Exercise 1
            href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1.html
          - text: Hands-on Exercise 2
            href: Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2.html
          - text: Hands-on Exercise 3
            href: Hands-on_Ex/Hands-on_Ex3/Hands-on_Ex3.html
          - text: Hands-on Exercise 4
            href: Hands-on_Ex/Hands-on_Ex4/Hands-on_Ex4.html
          - text: Hands-on Exercise 5
            href: Hands-on_Ex/Hands-on_Ex5/Hands-on_Ex5.html
          - text: Hands-on Exercise 6
            href: Hands-on_Ex/Hands-on_Ex6/Hands-on_Ex6.html
          - text: Hands-on Exercise 7
            href: Hands-on_Ex/Hands-on_Ex7/Hands-on_Ex7.html
          - text: Hands-on Exercise 8
            href: Hands-on_Ex/Hands-on_Ex8/Hands-on_Ex8.html
          - text: Hands-on Exercise 9
            href: Hands-on_Ex/Hands-on_Ex9/Hands-on_Ex9.html
          - text: Hands-on Exercise 10
            href: Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html
      - text: "{{< iconify fxemoji redapple >}} In-class Exercises"
        menu: 
          - text: In-class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_Ex1.html
      - text: "{{< iconify fxemoji schoolsatchel >}} Take-home Exercises"
        menu: 
          - text: Take-home Exercise 1
            href: Take-home_Ex/Take-home_Ex1/Take-home_Ex1.html
          - text: Take-home Exercise 2
            href: Take-home_Ex/Take-home_Ex2/Take-home_Ex2.html
    right:
      - text: "{{< iconify fxemoji housebuilding >}}"
        href: "/"

format:
  html:
    theme: 
      - cosmo
      - theme.scss
    css: styles.css
    toc: true

editor: visual

