project:
  type: website

website:
  title: "spacebun"
  image: "images/spacebunny-banner.svg"
  favicon: "images/spacebunny.svg"
  page-navigation: true
  navbar:
    logo: "images/spacebunny-banner.png"
    title: false
    collapse-below: lg
    background: "#30638E"
    search: true
    left: 
      - text: "{{< iconify fxemoji leftwritinghand >}} Hands-on Exercises"
        menu: 
          - text: Hands-on Exercise 1
            href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1.html
          - text: Hands-on Exercise 2
            href: Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2.html
      - text: "{{< iconify fxemoji redapple >}} In-class Exercises"
        menu: 
          - text: In-class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_Ex1.html
      - text: "{{< iconify fxemoji schoolsatchel >}} Take-home Exercises"
        menu: 
          - text: Take-home Exercise 1
            href: Take-home_Ex/Take-home_Ex1/Take-home_Ex1.html
    right:
      - text: "{{< iconify fxemoji housebuilding >}}"
        href: "/"

format:
  html:
    theme: 
      - cosmo
      - theme.scss
    css: styles.css
    toc: true

editor: visual

